### PR TITLE
Test - edited dryville_story.md file

### PR DESCRIPTION
**Pull request by surabhiupadhyay**
Added two sections in the dryville_story.md file

### CODE REVIEW

**Review by lindsayplatt — APPROVED** [review]
Great job, @surabhiupadhyay! You can move on to the next step.

**Comment by surabhiupadhyay** [comment]
Hey Carr, I was trying step 9, but it says:

_On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.Rhistory

nothing added to commit but untracked files present (use "git add" to track)_

Does it mean the loop is closed?

**Comment by lindsayplatt** [comment]
@surabhiupadhyay thanks for bring this issue up!

Before you continue, there are a couple of things I'd want to check:

1. If you run `git log`, can you see your most recent commit at the top of that list? It should say `Merge pull request #1 from surabhiupadhyay/main` or something similar. If you see that, then you are good to go and your loop is closed (you may have already pushed your changes). If not, continue with the troubleshooting steps below.
2. Try running `git pull upstream main` one more time. Then check `git status`. Does it say "Your branch is ahead of 'origin/main' by X commits" now? If so, yay! Perhaps it is updated now and there was just a lag. If this still not correct, go to the next step below.
3. If you run `git remote -v`, do you have both a `remote` and an `origin` setup? Paste below so I can help you set those up if they are not!

**Comment by surabhiupadhyay** [comment]
Hi Carr, thank you for replying, here is what I got.

1. It doesn't say merge pull request, when I run git log, I see this:

commit 023799f815cda4ca508892cc394fdf9188f3d0bb (HEAD -> main, upstream/main, origin/main, origin/HEAD)
Author: Surabhi Upadhyay <surabhiupadhyay7@gmail.com>
Date:   Sun Jun 2 13:01:36 2024 -0600

    add dryvilles-first-water-works section

commit 5fbf430269ea140588869e3f53932f59bb5c9786
Author: Surabhi Upadhyay <surabhiupadhyay7@gmail.com>
Date:   Sun Jun 2 12:58:30 2024 -0600

    add getting-water-to-your-homes section

commit c6827ae9f86683da56a083e3eece42fd74b74545
Author: Lindsay (Carr) Platt <lplatt@cuahsi.org>
Date:   Thu May 30 16:13:49 2024 -0500

    Initial setup

commit 594b0b52e6c51de5c860a9822c7a382c60fcc4af
Author: Lindsay (Carr) Platt <lplatt@cuahsi.org>
Date:   Thu May 30 16:13:18 2024 -0500

2. I also tried running git pull upstream main one more time, but it shows the same. 

3. If I run git remote -v, I have origin and upstream. These are what I got.
origin	git@github.com:surabhiupadhyay/learning-gitflows-surabhiupadhyay.git (fetch)
origin	git@github.com:surabhiupadhyay/learning-gitflows-surabhiupadhyay.git (push)
upstream	git@github.com:surabhiupadhyay/learning-gitflows-surabhiupadhyay.git (fetch)
upstream	git@github.com:surabhiupadhyay/learning-gitflows-surabhiupadhyay.git (push)

**Comment by lindsayplatt** [comment]
Ah ok, I think that is the issue. You `upstream` remote is set to the same repo as your `origin`. So, `origin` is supposed to point to your fork (and yours looks correct!) but your `upstream` should point to `git@github.com:CUAHSI-GitFlows-Learners/learning-gitflows-surabhiupadhyay`. This was described in Step 4. Run the following and then try those steps again:

```
git remote set-url upstream git@github.com:CUAHSI-GitFlows-Learners/learning-gitflows-surabhiupadhyay.git
```

Then, when you run `git remote -v` you should see the following print out. It's a subtle but important difference because `upstream` should point to the canonical repo and `origin` should point to your fork. Refer to the diagram from Step 1 for a visual of this.

```
origin [git@github.com](mailto:git@github.com):surabhiupadhyay/learning-gitflows-surabhiupadhyay.git (fetch)
origin [git@github.com](mailto:git@github.com):surabhiupadhyay/learning-gitflows-surabhiupadhyay.git (push)
upstream [git@github.com](mailto:git@github.com):CUAHSI-GitFlows-Learners/learning-gitflows-surabhiupadhyay (fetch)
upstream [git@github.com](mailto:git@github.com):CUAHSI-GitFlows-Learners/learning-gitflows-surabhiupadhyay (push)
```

**Comment by surabhiupadhyay** [comment]
@lindsayplatt thank you for your help. It works now, I might have missed that step. 

With that, I just finished step 9 where I closed the loop between the main repo and my local copy!

**Comment by lindsayplatt** [comment]
@surabhiupadhyay great- thanks! You are good to continue :)

**Comment by surabhiupadhyay** [comment]
@lindsayplatt thanks - I am in Step 11 now.

**Comment by lindsayplatt** [comment]
@surabhiupadhyay - thanks. You are all to good keep moving beyond step 11 now!

**Pull request merged**
